# Application bootstrap — DB properties will be added with the persistence layer

# API
springdoc.api-docs-groups.enabled=true
springdoc.swagger-ui.path=/openapi-doc/openapi-ui.html
springdoc.api-docs.path=/openapi-doc/v3/api-docs
